version: '3'

services:
    db:
        image: postgres
        ports:
            - "5432:5432"

    web:
        build: .
        # command:
        #    /bin/bash -c "sleep 5 && python3 manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db
        ports:
            - "8000:8000"
        volumes:
            - .:/code/