version: '3'

services:
    db:
        image: postgres
        ports:
            - "5432:5432"

    web:
        build: .
        depends_on:
            - db
        ports:
            - "8000:8000"
        volumes:
            - .:/code/