# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_name',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
