# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_posts_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='message_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
