# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_posts_message_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-creation_date']},
        ),
    ]
