# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20170717_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='message',
            field=models.CharField(max_length=254),
        ),
    ]
