# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20170815_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author_profile_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='author_username',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
