# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=40)),
                ('password_hash', models.CharField(max_length=32)),
                ('salt_hash', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('about', models.CharField(max_length=100)),
            ],
        ),
    ]
