# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('user', '0002_auto_20170629_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='posts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Posts'),
        ),
    ]
