# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20170703_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(to='user.Users'),
        ),
    ]
