# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_users_profile_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-user_name']},
        ),
    ]
