# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0006_auto_20170717_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(unique=True)),
                ('author_id', models.IntegerField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('like_count', models.IntegerField(default=0)),
                ('report_count', models.IntegerField(default=0)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Posts')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
