# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author_name',
            field=models.CharField(default='Billy Bob', max_length=40),
            preserve_default=False,
        ),
    ]
